[experiment]
task = "cifar10"
seed = 42
device = "cuda"

[model]
arch = "resnet18_cifar"
num_classes = 10

[data]
batch_size = 256
num_workers = 5
aug = true
cutout = true
n_holes = 1
cutout_length = 16

[optimizer]
name = "AdamW"
lr = 0.01 # 极限学习率
weight_decay = 5e-4
betas = [0.9, 0.999]

[train]
epochs = 50
log_every = 10
ckpt_every = 50