[experiment]
task = "wikitext2_grad_accum"
seed = 42
device = "cuda"

[model]
arch = "nano_gpt"
vocabulary_size = 40479
embedding_size = 768
sequence_length = 256
num_heads = 12
num_layers = 4

[data]
batch_size = 8
num_workers = 4
tokenizer_path = "./data/wikitext2_tokenizer.json"

[optimizer]
name = "F3EPI"
lr = 0.0001
weight_decay = 0.1
betas = [0.9, 0.999]
alpha = 1.0
gamma = 1.0
accumulation_steps = 8 # 虚拟批次大小 = 8 * 8 = 64

[train]
epochs = 30
log_every = 10
ckpt_every = 2

[early_stop]
patience = 10
threshold = 1.0